workflows:
  ios_appstore_ipa:
    name: iOS App Store IPA
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_connect # Для загрузки в TestFlight/AppStore (если нужно)
        - signing          # ВАЖНО: Добавлена группа с вашими P12 и MobileProvision
      vars:
        XCODE_PROJECT: "Project-21-12-25-1.xcodeproj"
        XCODE_SCHEME: "Project-21-12-25-1"
        BUNDLE_ID: "com.danielian.selfcontrol.dopaminedetox"
        TEAM_ID: "AZSUVQUSS2"
        BUILD_NUM: "${CM_BUILD_NUMBER}"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: Show Xcode versions
        script: |
          xcodebuild -version
          swift --version || true

      - name: Initialize keychain
        script: |
          keychain initialize

      # ШАГ ИЗМЕНЕН: Вместо скачивания из Apple, берем из ваших секретов
      - name: Install Certificate and Profile from Secrets
        script: |
          # Декодируем P12 и добавляем в кейчейн
          echo $CERTIFICATE_P12 | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "$CERTIFICATE_PASSWORD"

          # Декодируем MobileProvision
          echo $MOBILEPROVISION | base64 --decode > /tmp/profile.mobileprovision
          
          # Копируем профиль в нужную папку
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Apply signing to Xcode project (only app targets)
        script: |
          # Применяем конкретный профиль из файла к таргету
          xcode-project use-profiles \
            --project "$XCODE_PROJECT" \
            --target "$XCODE_SCHEME" \
            --profile /tmp/profile.mobileprovision \
            --export-options-plist exportOptions.plist

      - name: Patch exportOptions.plist (ensure method/team/signingStyle)
        script: |
          /usr/libexec/PlistBuddy -c "Set :method $EXPORT_METHOD" exportOptions.plist || true
          /usr/libexec/PlistBuddy -c "Set :signingStyle manual" exportOptions.plist || true
          /usr/libexec/PlistBuddy -c "Set :teamID $TEAM_ID" exportOptions.plist || true
          
          # Важно: при ручной подписи иногда нужно явно указать профиль в plist
          # Но xcode-project use-profiles обычно справляется.
          
          echo "---- exportOptions.plist ----"
          /usr/libexec/PlistBuddy -c "Print" exportOptions.plist || true

      - name: Resolve SPM (optional)
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" || true

      - name: Archive
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          rm -rf "$ARCHIVE_PATH" || true

          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            COMPILER_INDEX_STORE_ENABLE=NO

          ls -lah "$CM_BUILD_DIR" || true
          test -d "$ARCHIVE_PATH"

      - name: Export IPA
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          EXPORT_PATH="$CM_EXPORT_DIR"

          mkdir -p "$EXPORT_PATH"

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_PATH"

          ls -lah "$EXPORT_PATH" || true
          test -e "$EXPORT_PATH"/*.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/*.xcarchive
      - exportOptions.plist
