workflows:
  ios_appstore_ipa:
    name: iOS App Store IPA
    max_build_duration: 90
    instance_type: mac_mini_m1

    environment:
      groups:
        - appstore_connect
      vars:
        XCODE_PROJECT: "Project-21-12-25-1.xcodeproj"
        XCODE_SCHEME: "Project-21-12-25-1"
        BUNDLE_ID: "com.danielian.selfcontrol.dopaminedetox"
        TEAM_ID: "AZSUVQUSS2"
        BUILD_NUM: "${CM_BUILD_NUMBER}"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: Show Xcode versions
        script: |
          xcodebuild -version
          swift --version || true

      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Fetch signing files (App Store) from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Apply signing to Xcode project (only app targets)
        script: |
          # Добавлен флаг --target, чтобы не ломать SPM зависимости
          xcode-project use-profiles \
            --project "$XCODE_PROJECT" \
            --target "$XCODE_SCHEME" \
            --export-options-plist exportOptions.plist

      - name: Patch exportOptions.plist (ensure method/team/signingStyle)
        script: |
          /usr/libexec/PlistBuddy -c "Set :method $EXPORT_METHOD" exportOptions.plist || true
          /usr/libexec/PlistBuddy -c "Set :signingStyle manual" exportOptions.plist || true
          /usr/libexec/PlistBuddy -c "Set :teamID $TEAM_ID" exportOptions.plist || true

          echo "---- exportOptions.plist ----"
          /usr/libexec/PlistBuddy -c "Print" exportOptions.plist || true

      - name: Resolve SPM (optional)
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" || true

      - name: Archive (NO manual signing flags here)
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          rm -rf "$ARCHIVE_PATH" || true

          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            COMPILER_INDEX_STORE_ENABLE=NO

          ls -lah "$CM_BUILD_DIR" || true
          test -d "$ARCHIVE_PATH"

      - name: Export IPA
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          EXPORT_PATH="$CM_EXPORT_DIR"

          mkdir -p "$EXPORT_PATH"

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_PATH"

          ls -lah "$EXPORT_PATH" || true
          test -e "$EXPORT_PATH"/*.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/*.xcarchive
      - exportOptions.plist
