workflows:
  ios_appstore_ipa:
    name: iOS App Store IPA
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_connect
        - signing
      vars:
        XCODE_PROJECT: "Project-21-12-25-1.xcodeproj"
        XCODE_SCHEME: "Project-21-12-25-1"
        BUNDLE_ID: "com.danielian.selfcontrol.dopaminedetox"
        TEAM_ID: "AZSUVQUSS2"
        BUILD_NUM: "${CM_BUILD_NUMBER}"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: Show Xcode versions
        script: |
          xcodebuild -version
          swift --version || true

      - name: Initialize keychain
        script: |
          keychain initialize

      - name: Install Certificate and Profile from Secrets
        script: |
          echo $CERTIFICATE_P12 | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "$CERTIFICATE_PASSWORD"

          echo $MOBILEPROVISION | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i /tmp/profile.mobileprovision))
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Resolve SPM (optional)
        script: |
          xcodebuild -resolvePackageDependencies \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" || true

      - name: Archive with Smart xcconfig (No Signing)
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          rm -rf "$ARCHIVE_PATH" || true

          # Отключаем подпись на этапе архивации
          echo "CODE_SIGNING_REQUIRED = NO" > build.xcconfig
          echo "CODE_SIGNING_ALLOWED = NO" >> build.xcconfig
          echo "CODE_SIGN_IDENTITY = " >> build.xcconfig
          echo "EXPANDED_CODE_SIGN_IDENTITY = " >> build.xcconfig
          echo "PROVISIONING_PROFILE_SPECIFIER = " >> build.xcconfig
          echo "DEVELOPMENT_TEAM = $TEAM_ID" >> build.xcconfig

          # ВАЖНО: Передаем версию через аргументы.
          # GENERATE_INFOPLIST_FILE=YES заставит Xcode создать/обновить plist с этими значениями.
          
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -xcconfig build.xcconfig \
            archive \
            MARKETING_VERSION="1.0" \
            CURRENT_PROJECT_VERSION="$BUILD_NUM" \
            GENERATE_INFOPLIST_FILE=YES \
            COMPILER_INDEX_STORE_ENABLE=NO \
            CODE_SIGN_STYLE="Manual"

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>$EXPORT_METHOD</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>$PROFILE_UUID</string>
              </dict>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          set -euo pipefail

          ARCHIVE_PATH="$CM_BUILD_DIR/${XCODE_SCHEME}.xcarchive"
          EXPORT_PATH="$CM_EXPORT_DIR"
          mkdir -p "$EXPORT_PATH"

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_PATH"

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/*.xcarchive
      - exportOptions.plist

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      
        key_id: $APP_STORE_CONNECT_KEY_ID            
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID      
        submit_to_testflight: true
