workflows:
  ios_appstore_manual_signing:
    name: iOS App Store Manual signing
    max_build_duration: 60

    environment:
      groups:
        - signing
        - appstore_connect
      vars:
        XCODE_PROJECT: "Trackify.xcodeproj"
        XCODE_SCHEME: "Trackify"
        BUNDLE_ID: "dev.annebunas.trackifyrrrr"
        TEAM_ID: "OVERRIDE_BY_PROFILE"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: "Import certificate and profile"
        script: |
          set -euo pipefail

          echo "$CERTIFICATE_P12" | base64 --decode > cert.p12
          echo "$MOBILEPROVISION" | base64 --decode > profile.mobileprovision

          keychain initialize
          if [ -n "${CERTIFICATE_PASSWORD:-}" ]; then
            keychain add-certificates --certificate cert.p12 --certificate-password "$CERTIFICATE_PASSWORD"
          else
            keychain add-certificates --certificate cert.p12
          fi

          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_PLIST="$(security cms -D -i profile.mobileprovision)"
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< "$PROFILE_PLIST")
          PROFILE_TEAM_ID=$(/usr/libexec/PlistBuddy -c 'Print TeamIdentifier:0' /dev/stdin <<< "$PROFILE_PLIST")

          cp profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"
          echo "Using Provisioning Profile UUID: $PROFILE_UUID"
          echo "TeamIdentifier from profile: $PROFILE_TEAM_ID"

          echo "PROFILE_UUID=$PROFILE_UUID" >> "$CM_ENV"
          echo "TEAM_ID=$PROFILE_TEAM_ID"   >> "$CM_ENV"

          echo "== Code signing identities in keychain =="
          security find-identity -v -p codesigning || true

          cat > exportOptions.plist <<EOI
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>${EXPORT_METHOD}</string>
            <key>teamID</key><string>${TEAM_ID}</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key><dict>
              <key>${BUNDLE_ID}</key><string>${PROFILE_UUID}</string>
            </dict>
            <key>compileBitcode</key><false/>
            <key>stripSwiftSymbols</key><true/>
            <key>destination</key><string>export</string>
          </dict></plist>
          EOI
          /usr/bin/plutil -lint exportOptions.plist

          xcode-project use-profiles --project "$XCODE_PROJECT" --export-options-plist exportOptions.plist

           - name: "Bump build (bash3-safe v3)"
        script: |
          #!/usr/bin/env bash
          set -euo pipefail

          # 0) Параметры и ручной оверрайд
          if [ -n "${XCODE_WORKSPACE:-}" ]; then
            PROJ_ARGS=(-workspace "$XCODE_WORKSPACE")
          else
            PROJ_ARGS=(-project "${XCODE_PROJECT:?Set XCODE_PROJECT or XCODE_WORKSPACE}")
          fi
          : "${XCODE_SCHEME:?Set XCODE_SCHEME}"
          : "${BUNDLE_ID:?Set BUNDLE_ID}"

          if [ -n "${INFO_PLIST:-}" ] && [ -f "$INFO_PLIST" ]; then
            PLIST="$INFO_PLIST"
          else
            PLIST=""
          fi

          # 1) SRCROOT и INFOPLIST_FILE из build settings
          if [ -z "${PLIST:-}" ]; then
            SETTINGS=$(xcodebuild "${PROJ_ARGS[@]}" -scheme "$XCODE_SCHEME" -configuration Release -showBuildSettings || true)
            SRCROOT=$(echo "$SETTINGS" | sed -n 's/^[[:space:]]*SRCROOT = \(.*\)$/\1/p' | head -n1)
            INFOPLIST_FILE_RAW=$(echo "$SETTINGS" | awk -F ' = ' '/^[[:space:]]*INFOPLIST_FILE /{print $2; exit}')
            SRCROOT=${SRCROOT:-"$PWD"}

            if [ -n "${INFOPLIST_FILE_RAW:-}" ]; then
              if [[ "$INFOPLIST_FILE_RAW" == /* ]]; then
                p="$INFOPLIST_FILE_RAW"
              elif [[ "$INFOPLIST_FILE_RAW" == \$\(SRCROOT\)* ]]; then
                p="${INFOPLIST_FILE_RAW/\$(SRCROOT)/$SRCROOT}"
              else
                p="$SRCROOT/$INFOPLIST_FILE_RAW"
              fi
              [ -f "$p" ] && PLIST="$p"
            fi
          fi

          # 2) Расширенный поиск по *.plist, где есть CFBundleIdentifier
          if [ -z "${PLIST:-}" ]; then
            prefer_exact=""
            prefer_var=""
            prefer_scheme=""
            first_ok=""

            # игнорируем Pods/Carthage/DerivedData
            find "$SRCROOT" \( -path "*/Pods/*" -o -path "*/Carthage/*" -o -path "*/DerivedData/*" \) -prune -o -type f -name "*.plist" -print0 2>/dev/null |
            while IFS= read -r -d '' f; do
              id=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$f" 2>/dev/null || true)
              [ -z "$id" ] && continue

              # первый подходящий не из .appex (запомним на всякий)
              if [ -z "$first_ok" ] && [[ "$f" != *.appex/* ]]; then
                first_ok="$f"
              fi

              # точное совпадение
              if [ "$id" = "$BUNDLE_ID" ]; then
                prefer_exact="$f"; break
              fi

              # содержит $(PRODUCT_BUNDLE_IDENTIFIER)
              case "$id" in *'$(PRODUCT_BUNDLE_IDENTIFIER)'*) [ -z "$prefer_var" ] && prefer_var="$f" ;; esac

              # путь содержит имя схемы
              case "$f" in *"$XCODE_SCHEME"*/Info*.plist) [ -z "$prefer_scheme" ] && prefer_scheme="$f" ;; esac
            done

            if   [ -n "$prefer_exact"  ]; then PLIST="$prefer_exact"
            elif [ -n "$prefer_var"    ]; then PLIST="$prefer_var"
            elif [ -n "$prefer_scheme" ]; then PLIST="$prefer_scheme"
            else PLIST="$first_ok"
            fi
          fi

          [ -n "${PLIST:-}" ] && [ -f "$PLIST" ] || { echo "❌ Не удалось найти Info plist для $BUNDLE_ID"; exit 1; }
          echo "✅ Using Info.plist: $PLIST"

          # 3) (опц.) маркетинговая версия из APP_VERSION
          if [ -n "${APP_VERSION:-}" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $APP_VERSION" "$PLIST" \
              || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $APP_VERSION" "$PLIST"
          fi

          # 4) Build — уникальный timestamp (только цифры)
          BUILD_NUM=$(date +%y%j%H%M%S)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" "$PLIST" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUM" "$PLIST"

          /usr/bin/plutil -lint "$PLIST"
          echo "== Final versions =="
          echo "CFBundleShortVersionString=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST" 2>/dev/null || echo '(unchanged)')"
          echo "CFBundleVersion=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST")"

      - name: "Archive and export IPA (xcodebuild)"
        script: |
          set -euo pipefail
          ARCHIVE_PATH="$CM_BUILD_DIR/Trackify.xcarchive"
          EXPORT_PATH="$CM_EXPORT_DIR"

          echo "Archiving to: $ARCHIVE_PATH"
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            COMPILER_INDEX_STORE_ENABLE=NO

          echo "Exporting IPA to: $EXPORT_PATH"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_PATH"

          echo "Export dir listing:"
          ls -lah "$EXPORT_PATH" || true
          test -e "$EXPORT_PATH"/*.ipa

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_EXPORT_DIR/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
